### ISSUE TITLE
term "Participant"

### ISSUE THREAD

**Issue by cturbelin** [influenzanet/influenzanet#1]
This term is already used in the current platform (and in the articles) and it refers to an individual for whom data are registered from any survey.
We use it to differentiate from the user who connects to the platform as several participants can belong to an account and the data collection for a participant can be delegated.
So it seems to be confusing to use this term as a Role for the platform.

**Comment by DanielDietzsch** [comment]
I removed the role "participant" since this role is not necessary.

**Comment by cturbelin** [comment]
Thank you ! yes it's a "Role" in the sense of the app but a "Concept"
