### ISSUE TITLE
Wiki : reorganize

### ISSUE THREAD

**Issue by cturbelin** [influenzanet/influenzanet#2]
- Do not explode docs in too many pages, we need a global view of the project, it's already  hard to read 
- Architecture would be better on one page rather than several : regroup client, Cloud service backend, Instance etc 
- User, Study, and concepts should be describe in one page (because they are strongly connected concepts (global naming convention page was created for that)
- Services should not be described on the technical level as they are already defined in proto files, we can use  https://github.com/pseudomuto/protoc-gen-doc to generate a technical documentation. Moreover they are not stable yet maintain this kind of doc will be hard.
- A page with an overview of all services and their respectives roles would be preferable to a tech description of each service for now

**Comment by DanielDietzsch** [comment]
I just adjusted the structure.  I hope this is better now.

**Comment by cturbelin** [comment]
Yes, much better thank you ! It's better to have a global view of the whole system in a quick read !
